{
  "Id": 50333094,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_SirenaW_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A02J'\r\nendfunction\r\n\r\nfunction Trig_SirenaW_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local integer lvl\r\n    local real dmg\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set lvl = udg_Level\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 300, \"enemy\", RT_ORGANIC, 0, 0 )\r\n        set lvl = udg_Level\r\n        call textst( udg_string[0] + GetObjectName('A02J'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set lvl = GetUnitAbilityLevel(caster, GetSpellAbilityId())\r\n    endif\r\n    set dmg = GetHeroStr( caster, true ) + GetHeroAgi( caster, true ) + GetHeroInt( caster, true ) + 5 + 5 * lvl\r\n    \r\n    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Undead\\\\AnimateDead\\\\AnimateDeadTarget.mdl\", target, \"origin\") )\r\n    call UnitDamageTarget( caster, target, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS )\r\n    if GetUnitState( target, UNIT_STATE_LIFE) <= 0.405 and combat( caster, false, 0 ) and not( udg_fightmod[3] ) then\r\n        call statst( caster, 0, 2, 0, 0, true )\r\n        set udg_Data[GetPlayerId(GetOwningPlayer(caster)) + 1 + 104] = udg_Data[GetPlayerId(GetOwningPlayer(caster)) + 1 + 104] + 2\r\n        call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Undead\\\\AnimateDead\\\\AnimateDeadTarget.mdl\", caster, \"origin\") )\r\n        call textst(\"|c0020FF20 +2 agility\", caster, 64 , 90 , 10 , 1)\r\n    endif\r\n    \r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_SirenaW takes nothing returns nothing\r\n    set gg_trg_SirenaW = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_SirenaW, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_SirenaW, Condition( function Trig_SirenaW_Conditions ) )\r\n    call TriggerAddAction( gg_trg_SirenaW, function Trig_SirenaW_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}