{
  "Id": 50333168,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_WagonE_Conditions takes nothing returns boolean\r\n    return GetLearnedSkill() == 'A0DN'\r\nendfunction\r\n\r\nfunction WagonECast takes nothing returns nothing\r\n    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n    local unit caster = LoadUnitHandle( udg_hash, id, StringHash( \"wgne\" ) )\r\n    local real money = LoadInteger( udg_hash, id, StringHash( \"wgne\" ) )\r\n    local real heal = LoadReal( udg_hash, id, StringHash( \"wgne\" ) )\r\n    local unit u\r\n    local integer cyclA\r\n    local real r = 200\r\n    local real g = 0.5\r\n    \r\n    if GetUnitState( caster, UNIT_STATE_LIFE) > 0.405 and not( IsUnitLoaded( caster ) ) and combat( caster, false, 0 ) then\r\n        if GetUnitAbilityLevel( caster, 'A0DN') > 0 then\r\n            call BlzStartUnitAbilityCooldown( caster, 'A0DN', 7 )\r\n        endif\r\n        set cyclA = 1\r\n        loop\r\n            exitwhen cyclA > 1\r\n            set u = randomtarget( caster, r, \"enemy\", 0, 0, 0 )\r\n            if u == null and r <= 1000 then\r\n                set cyclA = cyclA - 1\r\n                set r = r + 100\r\n                set g = g + 0.15\r\n            endif\r\n            set cyclA = cyclA + 1\r\n        endloop\r\n        if not(udg_fightmod[3]) then\r\n            call moneyst( caster, R2I(money*g) )\r\n        endif\r\n        call healst( caster, null, heal*g )\r\n    endif\r\n    \r\n    set caster = null\r\nendfunction\r\n\r\nfunction Trig_WagonE_Actions takes nothing returns nothing\r\n    local integer id = GetHandleId( GetLearningUnit() )\r\n    local integer money = 4 + (2*GetUnitAbilityLevel( GetLearningUnit(), 'A0DN' ))\r\n    local real heal = 4 + (4*GetUnitAbilityLevel( GetLearningUnit(), 'A0DN' ))\r\n    \r\n    if LoadTimerHandle( udg_hash, id, StringHash( \"wgne\" ) ) == null then\r\n        call SaveTimerHandle( udg_hash, id, StringHash( \"wgne\" ), CreateTimer() )\r\n    endif\r\n\tset id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"wgne\" ) ) ) \r\n\tcall SaveUnitHandle( udg_hash, id, StringHash( \"wgne\" ), GetLearningUnit() )\r\n    call SaveInteger( udg_hash, id, StringHash( \"wgne\" ), money )\r\n    call SaveReal( udg_hash, id, StringHash( \"wgne\" ), heal )\r\n\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( GetLearningUnit() ), StringHash( \"wgne\" ) ), 7, true, function WagonECast )\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_WagonE takes nothing returns nothing\r\n    set gg_trg_WagonE = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_WagonE, EVENT_PLAYER_HERO_SKILL )\r\n    call TriggerAddCondition( gg_trg_WagonE, Condition( function Trig_WagonE_Conditions ) )\r\n    call TriggerAddAction( gg_trg_WagonE, function Trig_WagonE_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}