{
  "Id": 50332483,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_North_Lotus_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A14M'\r\nendfunction\r\n\r\nfunction Trig_North_Lotus_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local integer cyclA = 1\r\n    local integer cyclAEnd \r\n    local integer rand\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"ally\", 0, 0, 0 )\r\n        call textst( udg_string[0] + GetObjectName('A11T'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n    endif\r\n\r\n    set cyclAEnd = eyest( caster )\r\n    loop\r\n        exitwhen cyclA > cyclAEnd\r\n        call healst( caster, target, 300 )\r\n        call DestroyEffect( AddSpecialEffectTarget( \"war3mapImported\\\\MiniRessurection.mdx\", target, \"origin\" ) )\r\n        if GetUnitState( target, UNIT_STATE_MAX_LIFE ) == GetUnitState( target, UNIT_STATE_LIFE ) and combat( caster, false, 0 ) then\r\n            set udg_RandomLogic = true\r\n            set udg_Caster = caster\r\n            set udg_Level = 5\r\n            set rand = GetRandomInt( 1, 3 )\r\n            set RandomMode = true\r\n            if rand == 1 then\r\n                call TriggerExecute( udg_DB_Trigger_One[GetRandomInt( 1, udg_Database_NumberItems[14])] )\r\n            elseif rand == 2 then\r\n                call TriggerExecute( udg_DB_Trigger_Two[GetRandomInt( 1, udg_Database_NumberItems[15])] )\r\n            else\r\n                call TriggerExecute( udg_DB_Trigger_Three[GetRandomInt( 1, udg_Database_NumberItems[16])] )\r\n            endif\r\n            set RandomMode = false\r\n        endif\r\n        set cyclA = cyclA + 1\r\n    endloop\r\n    \r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_North_Lotus takes nothing returns nothing\r\n    set gg_trg_North_Lotus = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_North_Lotus, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_North_Lotus, Condition( function Trig_North_Lotus_Conditions ) )\r\n    call TriggerAddAction( gg_trg_North_Lotus, function Trig_North_Lotus_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}