{
  "Id": 50332807,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_OrbDesecrated_Land_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A193'\r\nendfunction\r\n\r\nfunction Trig_OrbDesecrated_Land_Actions takes nothing returns nothing\r\n    local integer x\r\n    local unit caster\r\n    local unit target\r\n    local group g = CreateGroup()\r\n    local unit u\r\n    local real t\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set t = udg_Time\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"ally\", 0, 0, 0 )\r\n        call textst( udg_string[0] + GetObjectName('A193'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n        set t = 10\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set t = 10\r\n    endif\r\n    set t = timebonus(caster, t)\r\n    \r\n    set x = eyest( caster )\r\n    call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\NightElf\\\\Taunt\\\\TauntCaster.mdl\", target, \"origin\" ) )\r\n    call GroupEnumUnitsInRange( g, GetUnitX( target ), GetUnitY( target ), 450, null )\r\n    loop\r\n        set u = FirstOfGroup(g)\r\n        exitwhen u == null\r\n        if unitst( u, caster, \"enemy\" ) then\r\n            call taunt( target, u, t )\r\n        endif\r\n        call GroupRemoveUnit(g,u)\r\n    endloop\r\n    if not( IsUnitType(target, UNIT_TYPE_ANCIENT ) ) and not( IsUnitType(target, UNIT_TYPE_HERO ) ) then\r\n        call BlzSetUnitArmor( target, BlzGetUnitArmor(target)+BlzGetUnitArmor(caster) )\r\n    endif\r\n    \r\n    call GroupClear( g )\r\n    call DestroyGroup( g )\r\n    set u = null\r\n    set g = null\r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_OrbDesecrated_Land takes nothing returns nothing\r\n    set gg_trg_OrbDesecrated_Land = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_OrbDesecrated_Land, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_OrbDesecrated_Land, Condition( function Trig_OrbDesecrated_Land_Conditions ) )\r\n    call TriggerAddAction( gg_trg_OrbDesecrated_Land, function Trig_OrbDesecrated_Land_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}