{
  "Id": 50333301,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_MorlocQ_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A0TH'\r\nendfunction\r\n\r\nfunction Trig_MorlocQ_Actions takes nothing returns nothing\r\n    local real vam\r\n    local unit caster\r\n    local unit target\r\n    local unit old\r\n    local integer lvl\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set lvl = udg_Level\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, TARGET_ALLY, 0, 0, 0 )\r\n        set lvl = udg_Level\r\n        call textst( udg_string[0] + GetObjectName('A0TH'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n    endif\r\n    \r\n    set old = LoadUnitHandle( udg_hash, GetHandleId( caster ), StringHash( \"mrlq\" ) )\r\n    if old != null then\r\n        call UnitRemoveAbility( old, 'A0TD' )\r\n        call UnitRemoveAbility( old, 'B024' )\r\n    endif\r\n    \r\n    set vam = 0.1 + ( 0.15 * lvl )\r\n    \r\n    call UnitAddAbility( target, 'A0TD' )\r\n    call DestroyEffect( AddSpecialEffectTarget(\"Abilities\\\\Spells\\\\Orc\\\\Devour\\\\DevourEffectArt.mdl\", target, \"origin\" ) )\r\n    call SaveUnitHandle( udg_hash, GetHandleId( caster ), StringHash( \"mrlq\" ), target )\r\n    call SaveReal( udg_hash, GetHandleId( target ), StringHash( \"mrlqv\" ), vam )\r\n    \r\n    set caster = null\r\n    set target = null\r\n    set old = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_MorlocQ takes nothing returns nothing\r\n    set gg_trg_MorlocQ = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_MorlocQ, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_MorlocQ, Condition( function Trig_MorlocQ_Conditions ) )\r\n    call TriggerAddAction( gg_trg_MorlocQ, function Trig_MorlocQ_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}