{
  "Id": 50333180,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_Orb_Conditions takes nothing returns boolean\r\n    return GetUnitTypeId(GetEnteringUnit()) == 'u000' and GetUnitAbilityLevel(GetEnteringUnit(), 'A04J') > 0\r\nendfunction\r\n\r\nfunction OrbCast takes nothing returns nothing \r\n\tlocal integer id = GetHandleId( GetExpiredTimer( ) )\r\n    local unit caster = LoadUnitHandle( udg_hash, id, StringHash( \"orbc\" ) )\r\n    local unit orb = LoadUnitHandle( udg_hash, id, StringHash( \"orb\" ) )\r\n    local group g = CreateGroup()\r\n    local unit u\r\n\r\n    if IsUnitAlive(orb) then\r\n    \tcall GroupEnumUnitsInRange( g, GetUnitX( orb ), GetUnitY( orb ), 182, null )\r\n    \tloop\r\n        \tset u = FirstOfGroup(g)\r\n        \texitwhen u == null\r\n        \tif unitst( u, orb, \"enemy\" ) then\r\n        \t    call UnitDamageTarget( caster, u, 5, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS )\r\n            elseif unitst( u, orb, \"ally\" ) then\r\n                call healst(caster, u, 5)\r\n        \tendif\r\n        \tcall GroupRemoveUnit(g,u)\r\n    \tendloop\r\n    else\r\n\t\tcall DestroyTimer( GetExpiredTimer() )\r\n    endif\r\n\r\n    call DestroyGroup( g )\r\n    set u = null\r\n    set orb = null\r\n    set g = null\r\n    set caster = null\r\nendfunction \r\n\r\nfunction Trig_Orb_Actions takes nothing returns nothing\r\n    local integer i = GetPlayerId(GetOwningPlayer(GetEnteringUnit())) + 1\r\n\tlocal integer id = GetHandleId( GetEnteringUnit() )\r\n    \r\n\tcall DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Human\\\\Invisibility\\\\InvisibilityTarget.mdl\", GetUnitX(GetEnteringUnit()), GetUnitY(GetEnteringUnit()) ) )\r\n    \r\n    call UnitApplyTimedLife( GetEnteringUnit(), 'BTLF', 30 )\r\n    \r\n\tcall SaveTimerHandle( udg_hash, id, StringHash( \"orb\" ), CreateTimer( ) ) \r\n\tset id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"orb\" ) ) ) \r\n\tcall SaveUnitHandle( udg_hash, id, StringHash( \"orb\" ), GetEnteringUnit() ) \r\n\tcall SaveUnitHandle( udg_hash, id, StringHash( \"orbc\" ), udg_hero[i] ) \r\n\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( GetEnteringUnit() ), StringHash( \"orb\" ) ), 1, true, function OrbCast ) \r\nendfunction \r\n\r\n//===========================================================================\r\nfunction InitTrig_Orb takes nothing returns nothing\r\n    set gg_trg_Orb = CreateTrigger(  )\r\n    call TriggerRegisterEnterRectSimple( gg_trg_Orb, GetWorldBounds() )\r\n    call TriggerAddCondition( gg_trg_Orb, Condition( function Trig_Orb_Conditions ) )\r\n    call TriggerAddAction( gg_trg_Orb, function Trig_Orb_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}