{
  "Id": 50333199,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_MonkR_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A0NR'\r\nendfunction\r\n\r\nfunction MonkRCast takes nothing returns nothing\r\n    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n    local unit u = LoadUnitHandle( udg_hash, id, StringHash( \"mnkr\" ) )\r\n    \r\n    call UnitRemoveAbility( u, 'A0KE' )\r\n    call UnitRemoveAbility( u, 'B01O' )\r\n    call FlushChildHashtable( udg_hash, id )\r\n    \r\n    set u = null\r\nendfunction\r\n\r\nfunction Trig_MonkR_Actions takes nothing returns nothing\r\n    local integer cyclA = 1\r\n    local integer id\r\n    local integer lvl\r\n    local unit caster\r\n    local real t\r\n    local integer i\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set lvl = udg_Level\r\n        set t = udg_Time\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set lvl = udg_Level\r\n        call textst( udg_string[0] + GetObjectName('A0NR'), caster, 64, 90, 10, 1.5 )\r\n        set t = 30\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n        set t = 30\r\n    endif\r\n    set t = timebonus(caster, t)\r\n    \r\n    set id = GetHandleId( caster )\r\n    call UnitAddAbility( caster, 'A0KE' )\r\n    call DestroyEffect( AddSpecialEffectTarget(\"EarthDetonation.mdx\", caster, \"origin\" ) )\r\n    \r\n    if LoadTimerHandle( udg_hash, id, StringHash( \"mnkr\" ) ) == null then\r\n        call SaveTimerHandle( udg_hash, id, StringHash( \"mnkr\" ), CreateTimer() )\r\n    endif\r\n    set id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"mnkr\" ) ) ) \r\n    call SaveUnitHandle( udg_hash, id, StringHash( \"mnkr\" ), caster )\r\n    call SaveInteger( udg_hash, id, StringHash( \"mnkr\" ), 4 + ( 2 * lvl ) )\r\n    call TimerStart( LoadTimerHandle( udg_hash, GetHandleId( caster ), StringHash( \"mnkr\" ) ), t, false, function MonkRCast )\r\n    \r\n    set caster = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_MonkR takes nothing returns nothing\r\n    set gg_trg_MonkR = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_MonkR, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_MonkR, Condition( function Trig_MonkR_Conditions ) )\r\n    call TriggerAddAction( gg_trg_MonkR, function Trig_MonkR_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}