{
  "Id": 50332850,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "scope Rocks initializer init\r\n\r\n\tprivate function condition takes nothing returns boolean\r\n\t    local integer i = 0\r\n\t    local integer itemType = GetItemTypeId(GetManipulatedItem())\r\n\t    \r\n\t    loop\r\n\t        exitwhen i > 3\r\n\t        if itemType == 'III1' + i then\r\n\t            return true\r\n\t        endif\r\n\t        set i = i + 1\r\n\t    endloop\r\n\t    return false\r\n\tendfunction\r\n\t\r\n\tprivate function GainStat takes unit hero returns nothing\r\n\t\tlocal integer rand = GetRandomInt( 1, 3 )\r\n\t\r\n\t\tif rand == 1 then\r\n            call statst( hero, 1, 0, 0, 0, true )\r\n            call textst( \"|c00FF2020 +1 strength\", hero, 64, 90, 10, 1 )\r\n        elseif rand == 2 then\r\n            call statst( hero, 0, 1, 0, 0, true )\r\n            call textst( \"|c0020FF20 +1 agility\", hero, 64, 90, 10, 1 )\r\n        elseif rand == 3 then\r\n            call statst( hero, 0, 0, 1, 0, true )\r\n            call textst( \"|c002020FF +1 intelligence\", hero, 64, 90, 10, 1 )\r\n        endif\r\n\tendfunction\r\n\t\r\n\tprivate function DealDamage takes unit hero returns nothing\r\n\t\tlocal unit target = randomtarget( hero, 600, \"enemy\", 0, 0, 0 )\r\n\t\t\r\n\t\tif target == null then\r\n\t\t\treturn\r\n\t\tendif\r\n\r\n        call spectime(\"Abilities\\\\Spells\\\\Other\\\\BreathOfFire\\\\BreathOfFireMissile.mdl\", GetUnitX( target ), GetUnitY( target ), 1 )\r\n        call UnitDamageTarget( hero, target, 75, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n\r\n        set target = null\r\n\tendfunction\r\n\t\r\n\tprivate function action takes nothing returns nothing\r\n\t    local unit hero = GetManipulatingUnit()\r\n\t    local integer itemType = GetItemTypeId(GetManipulatedItem())\r\n\r\n\t    if itemType == 'III1' then\r\n\t        call healst( hero, null, 50 )\r\n\t        call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Human\\\\HolyBolt\\\\HolyBoltSpecialArt.mdl\", hero, \"origin\") )\r\n\t    elseif itemType == 'III2' then\r\n\t        call manast( hero, null, 25 )\r\n\t        call DestroyEffect( AddSpecialEffectTarget( \"Abilities\\\\Spells\\\\Items\\\\AIma\\\\AImaTarget.mdl\", hero, \"origin\") )\r\n\t    elseif itemType == 'III3' then\r\n\t        call DealDamage(hero)\r\n\t    else\r\n\t        call GainStat(hero)\r\n\t    endif\r\n\t    \r\n\t    set hero = null\r\n\tendfunction\r\n\t\r\n\t//===========================================================================\r\n\tprivate function init takes nothing returns nothing\r\n\t\tcall CreateNativeEvent( EVENT_PLAYER_UNIT_PICKUP_ITEM, function action, function condition )\r\n\tendfunction\r\n\r\nendscope",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}