{
  "Id": 50333144,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_PirateR_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A07X'\r\nendfunction\r\n\r\nfunction Trig_PirateR_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local integer lvl\r\n    local real dmg\r\n    local group g = CreateGroup()\r\n    local unit u\r\n    local real dur\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set lvl = udg_Level\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n        set lvl = udg_Level\r\n        call textst( udg_string[0] + GetObjectName('A07X'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n    endif\r\n    set dmg = 80 + ( 40 * lvl )\r\n    set dur = 1 + (0.5*lvl)\r\n        \r\n    call GroupEnumUnitsInRange( g, GetUnitX( target ), GetUnitY( target ), 300, null )\r\n    loop\r\n        set u = FirstOfGroup(g)\r\n        exitwhen u == null\r\n        if unitst( u, caster, \"enemy\" ) then\r\n            call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\", GetUnitX( u ), GetUnitY( u ) ) )\r\n            call UnitStun(caster, u, dur )\r\n            call UnitDamageTarget( caster, u, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n        endif\r\n        call GroupRemoveUnit(g,u)\r\n    endloop\r\n\r\n    call DestroyGroup( g )\r\n    set u = null\r\n    set g = null\r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_PirateR takes nothing returns nothing\r\n    set gg_trg_PirateR = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_PirateR, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_PirateR, Condition( function Trig_PirateR_Conditions ) )\r\n    call TriggerAddAction( gg_trg_PirateR, function Trig_PirateR_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}