{
  "Id": 50333088,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_SniperP_Conditions takes nothing returns boolean\r\n    return GetLearnedSkill() == 'A0LA'\r\nendfunction\r\n\r\nfunction SniperPCast takes nothing returns nothing\r\n    local integer id = GetHandleId( GetExpiredTimer( ) )\r\n    local unit u = LoadUnitHandle( udg_hash, id, StringHash( \"snp\" ) )\r\n    local integer lvl = GetUnitAbilityLevel( u, 'A0LA' )\r\n    \r\n    call UnitAddAbility( u, 'A18P' )\r\n    call UnitAddAbility( u, 'A18Q' )\r\n    call UnitAddAbility( u, 'A18R' )\r\n    call SetUnitAbilityLevel( u, 'A18Q', lvl )\r\n    call SetUnitAbilityLevel( u, 'A18R', lvl )\r\n    if GetUnitState( u, UNIT_STATE_LIFE) > 0.405 then\r\n        call DestroyEffect(AddSpecialEffectTarget(\"Abilities\\\\Spells\\\\Orc\\\\MirrorImage\\\\MirrorImageDeathCaster.mdl\", u, \"origin\" ) )\r\n    endif\r\n    \r\n    set u = null\r\nendfunction\r\n\r\nfunction Trig_SniperP_Actions takes nothing returns nothing\r\n    local integer id = GetHandleId( GetLearningUnit() )\r\n    \r\n    call UnitRemoveAbility( GetLearningUnit(), 'A18P' )\r\n    call UnitRemoveAbility( GetLearningUnit(), 'A18Q' ) \r\n    call UnitRemoveAbility( GetLearningUnit(), 'A18R' ) \r\n    call UnitRemoveAbility( GetLearningUnit(), 'B031' ) \r\n    \r\n    if LoadTimerHandle( udg_hash, id, StringHash( \"snp\" ) ) == null then\r\n        call SaveTimerHandle( udg_hash, id, StringHash( \"snp\" ), CreateTimer() )\r\n    endif\r\n\t//call SaveTimerHandle( udg_hash, id, StringHash( \"snp\" ), CreateTimer( ) ) \r\n\tset id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"snp\" ) ) ) \r\n\tcall SaveUnitHandle( udg_hash, id, StringHash( \"snp\" ), GetLearningUnit() ) \r\n\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( GetLearningUnit() ), StringHash( \"snp\" ) ), 4, false, function SniperPCast ) \r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_SniperP takes nothing returns nothing\r\n    set gg_trg_SniperP = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_SniperP, EVENT_PLAYER_HERO_SKILL )\r\n    call TriggerAddCondition( gg_trg_SniperP, Condition( function Trig_SniperP_Conditions ) )\r\n    call TriggerAddAction( gg_trg_SniperP, function Trig_SniperP_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}