{
  "Id": 50332962,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_ComandW_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A0UL'\r\nendfunction\r\n\r\nfunction ComandWCast takes nothing returns nothing\r\n    local integer id = GetHandleId( GetExpiredTimer() )\r\n    call UnitRemoveAbility( LoadUnitHandle( udg_hash, id, StringHash( \"comw\" ) ), 'A0UP' )\r\n    call UnitRemoveAbility( LoadUnitHandle( udg_hash, id, StringHash( \"comw\" ) ), 'B054' )\r\n    call FlushChildHashtable( udg_hash, id )\r\nendfunction\r\n\r\nfunction Trig_ComandW_Actions takes nothing returns nothing\r\n    local integer id \r\n    local unit caster\r\n    local unit target\r\n    local integer lvl\r\n    local real t\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set lvl = udg_Level\r\n        set t = udg_Time\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"ally\", 0, 0, 0 )\r\n        set lvl = udg_Level\r\n        set t = 20\r\n        call textst( udg_string[0] + GetObjectName('A0UL'), caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set lvl = GetUnitAbilityLevel(GetSpellAbilityUnit(), GetSpellAbilityId())\r\n        set t = 20\r\n    endif\r\n    set t = timebonus(caster, t)\r\n    \r\n    set id = GetHandleId( target )\r\n    \r\n    call UnitAddAbility( target, 'A0UP' )\r\n    call SetUnitAbilityLevel( target, 'A0UM', lvl )\r\n    call SetUnitAbilityLevel( target, 'A0UN', lvl )\r\n    \r\n    call SaveReal( udg_hash, GetHandleId( caster ), StringHash( \"comwm\" ), 1 - ( 0.1 + ( 0.1 * lvl ) ) )\r\n    \r\n    if LoadTimerHandle( udg_hash, id, StringHash( \"comw\" ) ) == null  then\r\n        call SaveTimerHandle( udg_hash, id, StringHash( \"comw\" ), CreateTimer() )\r\n    endif\r\n\tset id = GetHandleId( LoadTimerHandle( udg_hash, id, StringHash( \"comw\" ) ) ) \r\n\tcall SaveUnitHandle( udg_hash, id, StringHash( \"comw\" ), target )\r\n\tcall TimerStart( LoadTimerHandle( udg_hash, GetHandleId( target ), StringHash( \"comw\" ) ), t, false, function ComandWCast )\r\n    \r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_ComandW takes nothing returns nothing\r\n    set gg_trg_ComandW = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_ComandW, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_ComandW, Condition( function Trig_ComandW_Conditions ) )\r\n    call TriggerAddAction( gg_trg_ComandW, function Trig_ComandW_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}