{
  "Id": 50332904,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_Taunt_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A19P'\r\nendfunction\r\n\r\nfunction Trig_Taunt_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local real t\r\n    local integer x\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n        set t = udg_Time\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 600, \"enemy\", RT_ORGANIC, 0, 0 )\r\n        call textst( udg_string[0] + GetObjectName('A19P'), caster, 64, 90, 10, 1.5 )\r\n        set t = 6\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n        set t = 6\r\n    endif\r\n    set t = timebonus(caster, t)\r\n\r\n    if GetUnitAbilityLevel(target, 'B059') > 0 then\r\n        call dummyspawn( caster, 1, 0, 0, 0 )\r\n        call UnitDamageTarget( bj_lastCreatedUnit, target, 150, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n    endif\r\n    if GetUnitState( target, UNIT_STATE_LIFE) > 0.405 then\r\n        call DestroyEffect( AddSpecialEffectTarget(\"Abilities\\\\Spells\\\\NightElf\\\\Taunt\\\\TauntCaster.mdl\" , caster, \"origin\" ) )\r\n        call taunt( caster, target, t )\r\n    endif\r\n    \r\n    set caster = null\r\n    set target = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_Taunt takes nothing returns nothing\r\n    set gg_trg_Taunt = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_Taunt, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_Taunt, Condition( function Trig_Taunt_Conditions ) )\r\n    call TriggerAddAction( gg_trg_Taunt, function Trig_Taunt_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}