{
  "Id": 50332819,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_FirePot_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A04E'\r\nendfunction\r\n\r\nfunction Trig_FirePot_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local real dmg\r\n    local group g = CreateGroup()\r\n    local unit u\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n        call textst( \"|cf0FF2020 Fire\", udg_Caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n    endif\r\n\r\n    set dmg = 300 * udg_SpellDamagePotion[GetPlayerId( GetOwningPlayer( caster ) ) + 1]\r\n    \r\n    if inv( caster, 'I05S' ) > 0 then \r\n        call GroupEnumUnitsInRange( g, GetUnitX( target ), GetUnitY( target ), 400, null )\r\n        loop\r\n            set u = FirstOfGroup(g)\r\n            exitwhen u == null\r\n            if unitst( u, caster, \"enemy\" ) then\r\n                call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\", GetUnitX( u ), GetUnitY( u ) ) )\r\n                call UnitDamageTarget( caster, u, dmg+(GetUnitState( u, UNIT_STATE_MAX_LIFE)*0.03), true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS )\r\n            endif\r\n            call GroupRemoveUnit(g,u)\r\n        endloop\r\n    else\r\n        call UnitDamageTarget(caster, target, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n        call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\", GetUnitX( target ), GetUnitY( target ) ) )\r\n    endif\r\n    call potionst( caster )\r\n    \r\n    call DestroyGroup( g )\r\n    set g = null\r\n    set u = null\r\n    set target = null\r\n    set caster = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_FirePot takes nothing returns nothing\r\n    set gg_trg_FirePot = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_FirePot, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_FirePot, Condition( function Trig_FirePot_Conditions ) )\r\n    call TriggerAddAction( gg_trg_FirePot, function Trig_FirePot_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}