{
  "Id": 50332823,
  "Comment": "",
  "IsScript": true,
  "RunOnMapInit": false,
  "Script": "function Trig_VolcanoPot_Conditions takes nothing returns boolean\r\n    return GetSpellAbilityId() == 'A13W'\r\nendfunction\r\n\r\nfunction Trig_VolcanoPot_Actions takes nothing returns nothing\r\n    local unit caster\r\n    local unit target\r\n    local real dmg\r\n    local real heal\r\n    \r\n    if CastLogic() then\r\n        set caster = udg_Caster\r\n        set target = udg_Target\r\n    elseif RandomLogic() then\r\n        set caster = udg_Caster\r\n        set target = randomtarget( caster, 900, \"enemy\", 0, 0, 0 )\r\n        call textst( \"|cf0901010 Volcano\", udg_Caster, 64, 90, 10, 1.5 )\r\n        if target == null then\r\n            set caster = null\r\n            return\r\n        endif\r\n    else\r\n        set caster = GetSpellAbilityUnit()\r\n        set target = GetSpellTargetUnit()\r\n    endif\r\n\r\n    set dmg = 250 * udg_SpellDamagePotion[GetPlayerId( GetOwningPlayer( caster ) ) + 1]\r\n    set heal = 300 * udg_SpellDamagePotion[GetPlayerId( GetOwningPlayer( caster ) ) + 1]\r\n    \r\n    call UnitDamageTarget( caster, target, dmg, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_MAGIC, WEAPON_TYPE_WHOKNOWS)\r\n    set IsHealFromPotion = true\r\n    call healst( caster, null, heal )\r\n    call potionst( caster )\r\n    call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\", GetUnitX( target ), GetUnitY( target ) ) )\r\n    call DestroyEffect( AddSpecialEffect( \"Abilities\\\\Spells\\\\Other\\\\Incinerate\\\\FireLordDeathExplode.mdl\", GetUnitX( caster ), GetUnitY( caster ) ) )\r\n    \r\n    set target = null\r\n    set caster = null\r\nendfunction\r\n\r\n//===========================================================================\r\nfunction InitTrig_VolcanoPot takes nothing returns nothing\r\n    set gg_trg_VolcanoPot = CreateTrigger(  )\r\n    call TriggerRegisterAnyUnitEventBJ( gg_trg_VolcanoPot, EVENT_PLAYER_UNIT_SPELL_EFFECT )\r\n    call TriggerAddCondition( gg_trg_VolcanoPot, Condition( function Trig_VolcanoPot_Conditions ) )\r\n    call TriggerAddAction( gg_trg_VolcanoPot, function Trig_VolcanoPot_Actions )\r\nendfunction\r\n\r\n",
  "Events": [],
  "LocalVariables": [],
  "Conditions": [],
  "Actions": []
}